-- Migration: set all user passwords to 'password123'
-- WARNING: This will overwrite existing password hashes for all users.
-- After applying, users must login and reset their passwords or you should force a password reset.

BEGIN;

-- bcrypt hash for 'password123' (cost=12)
-- Generated by the developer tools: $2b$12$igZWZtynLfIj5Vlwcu2G/O2PwNkRIBCbfz5PHvAb0/HmsamedG79u

UPDATE users
SET password_hash = '$2b$12$igZWZtynLfIj5Vlwcu2G/O2PwNkRIBCbfz5PHvAb0/HmsamedG79u'
WHERE email IS NOT NULL;

COMMIT;

-- Notes:
-- 1) This sets the same password for all users. Consider running for specific emails instead
--    of all users in production: WHERE email IN ('a@...', 'b@...').
-- 2) To run via psql (PowerShell):
--    psql "postgresql://sowadmin:YourPassword@sow-db-server.postgres.database.azure.com:5432/sowdb?sslmode=require" -f set_all_passwords_password123.sql
